// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCilzDHmSRV3CYeDAOV6Q-MtRtBOD8P_Ig',
    appId: '1:1061009452216:android:614358ef5abc883827d84d',
    messagingSenderId: '1061009452216',
    projectId: 'haushaltsbuch-app-rm',
    storageBucket: 'haushaltsbuch-app-rm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ARP_VyXWiAVh7ocCgJfYuoP1on4YeWA',
    appId: '1:1061009452216:ios:24081de896b1f19027d84d',
    messagingSenderId: '1061009452216',
    projectId: 'haushaltsbuch-app-rm',
    storageBucket: 'haushaltsbuch-app-rm.firebasestorage.app',
    iosBundleId: 'com.example.haushaltsbuchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoYyz1mGDoR_ci_rs4jnGAT_95L4sMqOk',
    appId: '1:1061009452216:web:19178f6fe321374527d84d',
    messagingSenderId: '1061009452216',
    projectId: 'haushaltsbuch-app-rm',
    authDomain: 'haushaltsbuch-app-rm.firebaseapp.com',
    storageBucket: 'haushaltsbuch-app-rm.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoYyz1mGDoR_ci_rs4jnGAT_95L4sMqOk',
    appId: '1:1061009452216:web:19178f6fe321374527d84d',
    messagingSenderId: '1061009452216',
    projectId: 'haushaltsbuch-app-rm',
    authDomain: 'haushaltsbuch-app-rm.firebaseapp.com',
    storageBucket: 'haushaltsbuch-app-rm.firebasestorage.app',
  );

}